# Generated by Django 5.0.4 on 2024-06-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stage', models.CharField(max_length=100)),
                ('best_of', models.IntegerField()),
                ('player1_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1_name', to='myapp.player', to_field='full_name')),
                ('player1_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1_url', to='myapp.player', to_field='url')),
                ('player2_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2_name', to='myapp.player', to_field='full_name')),
                ('player2_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2_url', to='myapp.player', to_field='url')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frame', models.IntegerField()),
                ('player', models.IntegerField()),
                ('score', models.IntegerField()),
                ('fifty_plus_breaks_str', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.match')),
            ],
        ),
    ]
