# Generated by Django 5.0.4 on 2024-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_tournament_match_tournament_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='frames_scores',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
