# Generated by Django 5.0.4 on 2024-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_match_frames_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
